services:
  dabing-manager:
    image: manager
    container_name: dabing-manager
    ports:
      - "80:80"
    volumes:
      - root:/app/project_root
      - media:/media
    restart: unless-stopped