# Generated by Django 5.2.4 on 2025-07-28 12:39

import database.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_usercharacterstable_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercharactertemporary',
            name='image',
            field=models.ImageField(blank=True, default='static/no_thumbnail.png', max_length=512, null=True, upload_to=database.utils.HashedFilePath('image', 'images')),
        ),
    ]
