# Generated by Django 5.2.4 on 2025-07-29 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_usercharactertemporary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='dubbing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='database.dubbing'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(default='%(class)s Name', max_length=128),
        ),
        migrations.AlterField(
            model_name='scene',
            name='dubbing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='database.dubbing'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='name',
            field=models.CharField(default='%(class)s Name', max_length=128),
        ),
    ]
