# Generated by Django 5.2.4 on 2025-07-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_episode_dubbing_alter_episode_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='created',
            new_name='started',
        ),
        migrations.RenameField(
            model_name='scene',
            old_name='created',
            new_name='started',
        ),
    ]
