# Generated by Django 5.2.4 on 2025-07-29 09:19

import database.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_created_episode_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='created',
            field=models.DateTimeField(default=database.utils.today),
        ),
        migrations.AddField(
            model_name='scene',
            name='created',
            field=models.DateTimeField(default=database.utils.today),
        ),
        migrations.AlterField(
            model_name='episode',
            name='started',
            field=models.DateTimeField(default=database.utils.today),
        ),
        migrations.AlterField(
            model_name='scene',
            name='started',
            field=models.DateTimeField(default=database.utils.today),
        ),
    ]
