# Generated by Django 5.2.4 on 2025-07-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_episode_created_scene_created_alter_episode_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
