# Generated by Django 5.2.3 on 2025-09-16 22:29

import database.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_episode_created_alter_scene_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubbing',
            name='cover',
            field=models.ImageField(blank=True, default=None, max_length=512, null=True, upload_to=database.utils.HashedFilePath('cover', 'covers/dubbing')),
        ),
        migrations.AddField(
            model_name='episode',
            name='cover',
            field=models.ImageField(blank=True, default=None, max_length=512, null=True, upload_to=database.utils.HashedFilePath('cover', 'covers/episode')),
        ),
        migrations.AddField(
            model_name='scene',
            name='cover',
            field=models.ImageField(blank=True, default=None, max_length=512, null=True, upload_to=database.utils.HashedFilePath('cover', 'covers/scene')),
        ),
    ]
