# Generated by Django 5.2.3 on 2025-09-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_dubbing_cover_episode_cover_scene_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='file_url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='file_url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
