# Generated by Django 5.2.4 on 2025-07-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('avatar', models.URLField(max_length=512)),
            ],
        ),
    ]
