# Generated by Django 5.2.4 on 2025-07-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_discorduser_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
