# Generated by Django 5.2.4 on 2025-08-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0004_discorduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
