# Generated by Django 5.2.3 on 2025-09-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0005_discorduser_is_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='discorduser',
            name='avatar_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
