name: Release Dubbing Manager on Docker Hub

env:
  IMAGE_NAME: dubbing-manager

on:
  release:
    types: [published]

jobs:
  containerise-selfhosted:
    runs-on: [self-hosted, docker]
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Determine tag type (beta or latest)
        id: tag_type
        run: |
          if ${{ github.event.release.prerelease }}; then
            echo "tag=${{ steps.tag.outputs.tag }}-beta" >> $GITHUB_ENV
            echo "tag_name=beta" >> $GITHUB_ENV
          else
            echo "tag=${{ steps.tag.outputs.tag }}" >> $GITHUB_ENV
            echo "tag_name=latest" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.tag_name }}
            type=raw,value=${{ env.tag }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dockerhub
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          build-args: |
            IMAGE_NAME=${{ env.IMAGE_NAME }}

  containerise-fallback:
    if: failure()
    needs: containerise-selfhosted
    runs-on: ubuntu-latest
    steps:
      - name: Re-run workflow on GitHub-hosted runner
        run: echo "Fallback to hosted runner"
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: dawidd6/action-get-tag@v1
        id: tag
      - run: |
          if ${{ github.event.release.prerelease }}; then
            echo "tag=${{ steps.tag.outputs.tag }}-beta" >> $GITHUB_ENV
            echo "tag_name=beta" >> $GITHUB_ENV
          else
            echo "tag=${{ steps.tag.outputs.tag }}" >> $GITHUB_ENV
            echo "tag_name=latest" >> $GITHUB_ENV
          fi
        id: tag_type
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.tag_name }}
            type=raw,value=${{ env.tag }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dockerhub
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          build-args: |
            IMAGE_NAME=${{ env.IMAGE_NAME }}
